/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import java.awt.HeadlessException;
import java.awt.event.WindowEvent;
import java.awt.Toolkit;
import java.util.Random;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Nonrapak
 */
public class AddBook extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    // book_code2.setText("Q"+n2);
    public AddBook() {
        initComponents();
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        author_name = new javax.swing.JTextField();
        Insert_book = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Price = new javax.swing.JTextField();
        book_name1 = new javax.swing.JTextField();
        publisher = new javax.swing.JTextField();
        book_type = new javax.swing.JTextField();
        book_volume = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(java.awt.Color.white);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 670, -1, -1));

        jLabel14.setFont(new java.awt.Font("Mali", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("เล่มที่ :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 80, 40));

        jLabel6.setFont(new java.awt.Font("Mali", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ราคา :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 80, 40));

        jLabel9.setFont(new java.awt.Font("Mali", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ชื่อหนังสือ :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 140, 40));

        jLabel8.setFont(new java.awt.Font("Mali", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ประเภทหนังสือ :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 210, 40));

        jLabel10.setFont(new java.awt.Font("Mali", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ผู้เขียน :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 90, -1));

        jLabel12.setFont(new java.awt.Font("Mali", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("จำนวน :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 100, 40));

        jLabel13.setFont(new java.awt.Font("Mali", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("สำนักพิมพ์ :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 140, 40));

        author_name.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(author_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 390, 40));

        Insert_book.setFont(new java.awt.Font("Mali", 0, 24)); // NOI18N
        Insert_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        Insert_book.setText("เพิ่มหนังสือ");
        Insert_book.setBorder(null);
        Insert_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert_bookActionPerformed(evt);
            }
        });
        getContentPane().add(Insert_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 220, 60));

        Back.setFont(new java.awt.Font("Mali", 0, 20)); // NOI18N
        Back.setText("Back");
        Back.setBorder(null);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 660, 130, 60));

        Price.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, 140, 40));

        book_name1.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(book_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 390, 40));

        publisher.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 390, 40));

        book_type.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(book_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 390, 40));

        book_volume.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(book_volume, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 140, 40));

        quantity.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, 140, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pocket_monsters_2019_anime_logo_translation_by_sliter_ddomqsd-fullview.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, 50));

        jLabel3.setFont(new java.awt.Font("Mali", 0, 20)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG (1).jpg"))); // NOI18N
        jLabel3.setText("jLabel1");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        close();
        this.toBack();
        ManageBooks mb = new ManageBooks();
        mb.setVisible(true);
        mb.toFront();
    }//GEN-LAST:event_BackActionPerformed

    private void Insert_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insert_bookActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
         try {  
            String base_URL = "jdbc:mysql://";
            String server = "localhost";
            String db = "sukuna_book_store";
            String u = "root";
            String p = "12345678";
            String con_string = base_URL + server + "/" + db;
            Class.forName("com.mysql.jdbc.Driver");
        conn = DriverManager.getConnection(con_string,u,p);
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
           try {
           String sql = "INSERT  INTO managebooks values (?,?,?,?,?,?,?)"  ;
            PreparedStatement stmt = conn.prepareStatement(sql); //6
            stmt.setString(1, book_name1.getText());
            stmt.setString(2, book_volume.getText());
            stmt.setString(3, book_type.getText());
            stmt.setString(4, publisher.getText());
            stmt.setString(5, author_name.getText());
            stmt.setString(6, Price.getText());
            stmt.setString(7, quantity.getText());
            stmt.executeUpdate(); 
             } catch (SQLException ex) {
            Logger.getLogger(AddBook.class.getName()).log(Level.SEVERE, null, ex);
        }
             try
             {
            String sql2 = "INSERT  INTO managebooks_restore values (?,?,?,?,?,?,?)"  ;
            PreparedStatement stmt = conn.prepareStatement(sql2); //6
            stmt.setString(1, book_name1.getText());
            stmt.setString(2, book_volume.getText());
            stmt.setString(3, book_type.getText());
            stmt.setString(4, publisher.getText());
            stmt.setString(5, author_name.getText());
            stmt.setString(6, Price.getText());
            stmt.setString(7, quantity.getText());
            stmt.executeUpdate(); 
             JOptionPane.showMessageDialog(null, "เพิ่มข้อมูลสำเร็จ");
             }  catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null,  e.getMessage());
        }
    }//GEN-LAST:event_Insert_bookActionPerformed

    public void close()
    {
        WindowEvent closeWindows = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindows);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
       



        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Insert_book;
    private javax.swing.JTextField Price;
    private javax.swing.JTextField author_name;
    private javax.swing.JTextField book_name1;
    private javax.swing.JTextField book_type;
    private javax.swing.JTextField book_volume;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField publisher;
    private javax.swing.JTextField quantity;
    // End of variables declaration//GEN-END:variables

    private static class PrepareStatement {

      
    }
}
