/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import java.awt.HeadlessException;
import java.awt.event.WindowEvent;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Random;

/**
 *
 * @author Nonrapak
 */

public class AddMemberShip extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
 
    public AddMemberShip() {
        initComponents();
      Random();
    }
   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        RestoreSystem = new javax.swing.JLabel();
        Main = new javax.swing.JLabel();
        Membership = new javax.swing.JLabel();
        ManagementSystem = new javax.swing.JLabel();
        LogIn = new javax.swing.JLabel();
        Main1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        call_member1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        adress_member = new javax.swing.JTextField();
        personal_code = new javax.swing.JTextField();
        last_name_member = new javax.swing.JTextField();
        member_name = new javax.swing.JTextField();
        member_code = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Female = new javax.swing.JRadioButton();
        Male = new javax.swing.JRadioButton();
        Insert_book = new javax.swing.JButton();
        Back1 = new javax.swing.JButton();
        register_member = new com.toedter.calendar.JDateChooser();
        Birth_day = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(java.awt.Color.white);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pocket_monsters_2019_anime_logo_translation_by_sliter_ddomqsd-fullview.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pikcachu.gif"))); // NOI18N

        RestoreSystem.setFont(new java.awt.Font("Angsana New", 3, 24)); // NOI18N
        RestoreSystem.setForeground(new java.awt.Color(83, 109, 254));
        RestoreSystem.setText("จัดการระบบคืน");
        RestoreSystem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RestoreSystemMouseClicked(evt);
            }
        });

        Main.setFont(new java.awt.Font("Angsana New", 3, 24)); // NOI18N
        Main.setForeground(new java.awt.Color(83, 109, 254));
        Main.setText("หน้าหลัก");
        Main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainMouseClicked(evt);
            }
        });

        Membership.setFont(new java.awt.Font("Angsana New", 3, 24)); // NOI18N
        Membership.setForeground(new java.awt.Color(83, 109, 254));
        Membership.setText("จัดการระบบสมาชิก");
        Membership.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MembershipMouseClicked(evt);
            }
        });

        ManagementSystem.setFont(new java.awt.Font("Angsana New", 3, 24)); // NOI18N
        ManagementSystem.setForeground(new java.awt.Color(83, 109, 254));
        ManagementSystem.setText("จัดการระบบเช่า");
        ManagementSystem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManagementSystemMouseClicked(evt);
            }
        });

        LogIn.setFont(new java.awt.Font("Angsana New", 3, 24)); // NOI18N
        LogIn.setForeground(new java.awt.Color(83, 109, 254));
        LogIn.setText("ออกจากระบบ");
        LogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogInMouseClicked(evt);
            }
        });

        Main1.setFont(new java.awt.Font("Angsana New", 3, 24)); // NOI18N
        Main1.setForeground(new java.awt.Color(83, 109, 254));
        Main1.setText("จัดการหนังสือ");
        Main1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Main1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(Main)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Main1)
                .addGap(10, 10, 10)
                .addComponent(Membership)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ManagementSystem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RestoreSystem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LogIn)
                .addGap(17, 17, 17)
                .addComponent(jLabel11))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Main)
                    .addComponent(Membership)
                    .addComponent(RestoreSystem)
                    .addComponent(ManagementSystem)
                    .addComponent(LogIn)
                    .addComponent(Main1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 670, -1, -1));

        call_member1.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(call_member1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, 390, 30));

        jLabel17.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 153, 0));
        jLabel17.setText("เบอร์โทร :");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, 110, 30));

        jLabel16.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 153, 0));
        jLabel16.setText("วันที่สมัคสมาชิก :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 170, 30));

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 153, 0));
        jLabel15.setText("ที่อยู่ :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 90, 30));

        jLabel14.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 153, 0));
        jLabel14.setText("วัน / ปี / เกิด :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 160, 30));

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 0));
        jLabel13.setText("นามสกุล :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 140, 30));

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 0));
        jLabel12.setText("รหัสบัตรประชาชน :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 200, 30));

        jLabel9.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("ชื่อสมาชิก :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 140, 30));

        adress_member.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(adress_member, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 390, 30));

        personal_code.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(personal_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 390, 30));

        last_name_member.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(last_name_member, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 390, 30));

        member_name.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(member_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 390, 30));

        member_code.setEditable(false);
        member_code.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(member_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 390, 30));

        jLabel10.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 0));
        jLabel10.setText("รหัสสมาชิก :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 130, 30));

        Female.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        Female.setForeground(new java.awt.Color(255, 0, 255));
        Female.setText("Female");
        Female.setBorder(null);
        Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleActionPerformed(evt);
            }
        });
        getContentPane().add(Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 290, 80, 40));

        Male.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        Male.setForeground(new java.awt.Color(0, 0, 255));
        Male.setText("Male");
        Male.setBorder(null);
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });
        getContentPane().add(Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 60, 40));

        Insert_book.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        Insert_book.setForeground(new java.awt.Color(0, 0, 204));
        Insert_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-2493635_960_720.png"))); // NOI18N
        Insert_book.setText("เพิ่มสมาชิก");
        Insert_book.setBorder(null);
        Insert_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert_bookActionPerformed(evt);
            }
        });
        getContentPane().add(Insert_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 220, 60));

        Back1.setFont(new java.awt.Font("Lucida Sans", 0, 20)); // NOI18N
        Back1.setForeground(new java.awt.Color(0, 0, 255));
        Back1.setText("Back");
        Back1.setBorder(null);
        Back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back1ActionPerformed(evt);
            }
        });
        getContentPane().add(Back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 660, 130, 60));
        getContentPane().add(register_member, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 620, 210, 30));
        getContentPane().add(Birth_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 210, 30));

        jLabel3.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG (2).jpg"))); // NOI18N
        jLabel3.setText("jLabel1");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

      
    
    private void MembershipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MembershipMouseClicked
        // TODO add your handling code here:
        close();
        ManageMembership ms = new ManageMembership();
        ms.setVisible(true);
        
    }//GEN-LAST:event_MembershipMouseClicked

    private void MainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainMouseClicked
        // TODO add your handling code here:
      close();
      Main m = new Main();
      m.setVisible(true);
    }//GEN-LAST:event_MainMouseClicked

    private void ManagementSystemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManagementSystemMouseClicked
        // TODO add your handling code here:
      close();
      AddMemberShip ms = new AddMemberShip();
      ms.setVisible(true);
        
    }//GEN-LAST:event_ManagementSystemMouseClicked

    private void LogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInMouseClicked
        // TODO add your handling code here:
        close();
        Login lg = new Login();
        lg.setVisible(true);
    }//GEN-LAST:event_LogInMouseClicked

    private void RestoreSystemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestoreSystemMouseClicked
        // TODO add your handling code here:
        close();
        buy_book rs = new buy_book();
        rs.setVisible(true);
        
    }//GEN-LAST:event_RestoreSystemMouseClicked

    private void Main1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Main1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Main1MouseClicked

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        // TODO add your handling code here:
        if(Male.isSelected())
        {
            Female.setSelected(false);
             gender = "M";
        }
       
    }//GEN-LAST:event_MaleActionPerformed

    private void FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleActionPerformed
        // TODO add your handling code here:
        if(Female.isSelected())
        {
            Male.setSelected(false);
             gender = "F";
        }
    }//GEN-LAST:event_FemaleActionPerformed

    private void Insert_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insert_bookActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String birhDay = sdf.format(Birth_day.getDate());
        String Register = sdf.format(register_member.getDate());
        Connection conn = null;
        try {
            String base_URL = "jdbc:mysql://";
            String server = "localhost";
            String db = "sukuna_book_store";
            String u = "root";
            String p = "12345678";
            String con_string = base_URL + server + "/" + db;
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(con_string,u,p);
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        String sql = "INSERT INTO managemember values ( ?,?,?,?,?,?,?,?,? )"  ;

        try {
            PreparedStatement stmt = conn.prepareStatement(sql); //6
            stmt.setString(1, member_code.getText());
            stmt.setString(2, member_name.getText());
            stmt.setString(3, last_name_member.getText());
            stmt.setString(4, personal_code.getText());
            stmt.setString(5, birhDay);
            stmt.setString(6, gender);
            stmt.setString(7, adress_member.getText());
            stmt.setString(8, call_member1.getText());
            stmt.setString(9,Register);

            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "เพิ่มข้อมูลสำเร็จ");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null,  e.getMessage());
        }
    }//GEN-LAST:event_Insert_bookActionPerformed

    private void Back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back1ActionPerformed
        // TODO add your handling code here:
        close();
        this.toBack();
        ManageMembership mbs = new ManageMembership();
        mbs.setVisible(true);
        mbs.toFront();
    }//GEN-LAST:event_Back1ActionPerformed
    public void Random()
      {
          Random rand = new Random();
           int rand_int1 = rand.nextInt(50);
           member_code.setText("000"+rand_int1);
          if( rand_int1 == rand_int1)
          {
               int rand_int2 = rand.nextInt(50);
               member_code.setText("000"+rand_int2);
               
          } 
      }
    public void close()
    {
        WindowEvent closeWindows = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindows);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMemberShip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMemberShip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMemberShip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMemberShip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
       



        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMemberShip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back1;
    private com.toedter.calendar.JDateChooser Birth_day;
    private javax.swing.JRadioButton Female;
    private javax.swing.JButton Insert_book;
    private javax.swing.JLabel LogIn;
    private javax.swing.JLabel Main;
    private javax.swing.JLabel Main1;
    private javax.swing.JRadioButton Male;
    private javax.swing.JLabel ManagementSystem;
    private javax.swing.JLabel Membership;
    private javax.swing.JLabel RestoreSystem;
    private javax.swing.JTextField adress_member;
    private javax.swing.JTextField call_member1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField last_name_member;
    private javax.swing.JTextField member_code;
    private javax.swing.JTextField member_name;
    private javax.swing.JTextField personal_code;
    private com.toedter.calendar.JDateChooser register_member;
    // End of variables declaration//GEN-END:variables

    private static class PrepareStatement {
    }
    private String gender;
}
