/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import java.awt.HeadlessException;
import java.awt.event.WindowEvent;
import java.awt.Toolkit;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Nonrapak
 */
public class buy_book extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
  
    
    public buy_book() {
        initComponents();
        
    }
     public void search_code()
     {
         Connection conn = null;
        try {
            String base_URL = "jdbc:mysql://";
            String server = "localhost";
            String db = "sukuna_book_store";
            String u = "root";
            String p = "12345678";
            String con_string = base_URL + server + "/" + db;
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(con_string, u, p);
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        try
        {
            String sql = "SELECT * FROM managemember WHERE member_code = '"+member_code_jtext.getText()+"'";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            while(rs.next()){
                member_name_jtext1.setText(rs.getString("member_name"));
                member_Lastname_jtext2.setText(rs.getString("member_lastname"));
                member_phone_jtext3.setText(rs.getString("call_number"));
                member_gender_jtext4.setText(rs.getString("gender"));
            }
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        price_cal_jtext9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        call_number1 = new javax.swing.JLabel();
        last_name = new javax.swing.JLabel();
        books_price_jtext5 = new javax.swing.JTextField();
        member_gender_jtext4 = new javax.swing.JTextField();
        member_phone_jtext3 = new javax.swing.JTextField();
        member_Lastname_jtext2 = new javax.swing.JTextField();
        member_name_jtext1 = new javax.swing.JTextField();
        Name = new javax.swing.JLabel();
        calculate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        calculate1 = new javax.swing.JButton();
        vat_jtext8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Withdrawal = new javax.swing.JTextField();
        price_jtext7 = new javax.swing.JTextField();
        quantity_jtext6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        books_volume_jtext6 = new javax.swing.JTextField();
        book_type_jtext2 = new javax.swing.JTextField();
        book_name_jtext1 = new javax.swing.JTextField();
        member_code_jtext = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        call_number2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Back_To_Main = new javax.swing.JButton();
        date_sell = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(java.awt.Color.white);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        price_cal_jtext9.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(price_cal_jtext9, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 500, 90, 30));

        jLabel12.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("จำนวนเงิน :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 500, 120, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pocket_monsters_2019_anime_logo_translation_by_sliter_ddomqsd-fullview.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, 50));

        gender.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        gender.setForeground(new java.awt.Color(255, 255, 255));
        gender.setText("Gender :");
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 230, -1, 30));

        call_number1.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        call_number1.setForeground(new java.awt.Color(255, 255, 255));
        call_number1.setText("วันที่ขาย :");
        getContentPane().add(call_number1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 90, 30));

        last_name.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        last_name.setForeground(new java.awt.Color(255, 255, 255));
        last_name.setText("Last Name :");
        getContentPane().add(last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, 30));

        books_price_jtext5.setEditable(false);
        books_price_jtext5.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(books_price_jtext5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 90, 30));

        member_gender_jtext4.setEditable(false);
        member_gender_jtext4.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(member_gender_jtext4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 230, 90, 30));

        member_phone_jtext3.setEditable(false);
        member_phone_jtext3.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(member_phone_jtext3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, 180, 30));

        member_Lastname_jtext2.setEditable(false);
        member_Lastname_jtext2.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(member_Lastname_jtext2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 180, 30));

        member_name_jtext1.setEditable(false);
        member_name_jtext1.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(member_name_jtext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 180, 30));

        Name.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Name :");
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, 30));

        calculate.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        calculate.setText("คำนวนราคา");
        calculate.setBorder(null);
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });
        getContentPane().add(calculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 630, 120, 40));

        jButton1.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        jButton1.setText("ตกลง");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, 120, 40));

        jLabel4.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        jLabel4.setText("รหัสสมาชิก :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 120, 30));

        jLabel9.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("เงินถอน :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 560, 90, 30));

        calculate1.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        calculate1.setText("ยืนยัน");
        calculate1.setBorder(null);
        calculate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculate1ActionPerformed(evt);
            }
        });
        getContentPane().add(calculate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 630, 120, 40));

        vat_jtext8.setEditable(false);
        vat_jtext8.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(vat_jtext8, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 400, 90, 30));

        jLabel11.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ภาษี :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 400, 60, 30));

        Withdrawal.setEditable(false);
        Withdrawal.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        Withdrawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawalActionPerformed(evt);
            }
        });
        getContentPane().add(Withdrawal, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 560, 90, 30));

        price_jtext7.setEditable(false);
        price_jtext7.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(price_jtext7, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 450, 90, 30));

        quantity_jtext6.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(quantity_jtext6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, 90, 30));

        jLabel8.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("จำนวน :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 70, 30));

        books_volume_jtext6.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(books_volume_jtext6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 90, 30));

        book_type_jtext2.setEditable(false);
        book_type_jtext2.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(book_type_jtext2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 140, 30));

        book_name_jtext1.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(book_name_jtext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 260, 30));

        member_code_jtext.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(member_code_jtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 260, 30));

        jButton3.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        jButton3.setText("ตกลง");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 310, 120, 40));

        jLabel10.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("รวม :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, 60, 30));

        jLabel7.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ราคา :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 70, 30));

        jLabel6.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ประเภท :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 100, 30));

        jLabel5.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("เล่มที่ :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 70, 30));

        jLabel3.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ชื่อหนังสือ :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 100, 30));

        call_number2.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        call_number2.setForeground(new java.awt.Color(255, 255, 255));
        call_number2.setText("Phone :");
        getContentPane().add(call_number2, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 230, 70, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ชื่อหนังสือ", "เล่มที่", "ประเภท", "ราคา", "จำนวน", "ภาษี", "รวม", "จำนวนเงิน", "เงินถอน"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 650, 260));

        Back_To_Main.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        Back_To_Main.setText("Back ");
        Back_To_Main.setBorder(null);
        Back_To_Main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_To_MainActionPerformed(evt);
            }
        });
        getContentPane().add(Back_To_Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 680, 90, 40));

        date_sell.setDateFormatString("d MMM , yyyy");
        getContentPane().add(date_sell, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 160, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG3.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         search_code();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
        int quantity = Integer.parseInt(quantity_jtext6.getText());
        int price = Integer.parseInt(books_price_jtext5.getText());
        vat_jtext8.setText("7%");
        int result = (quantity*price);
        int result_vat = result*(7)/100;
        int result_final = result_vat+result;
        price_jtext7.setText(""+result_final);
        int price_cal = Integer.parseInt(price_cal_jtext9.getText());
        int price_final = price_cal - result_final;
        Withdrawal.setText(""+price_final);
       
      
       
    }//GEN-LAST:event_calculateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         Connection conn = null;
        try {
            String base_URL = "jdbc:mysql://";
            String server = "localhost";
            String db = "sukuna_book_store";
            String u = "root";
            String p = "12345678";
            String con_string = base_URL + server + "/" + db;
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(con_string, u, p);
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        try
        {
            String sql = "SELECT * FROM managebooks_restore WHERE book_name='"+book_name_jtext1.getText()+"'and book_volume='"+books_volume_jtext6.getText()+"'";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            while(rs.next()){
                book_type_jtext2.setText(rs.getString("book_type"));
                books_price_jtext5.setText(rs.getString("price"));
                
            }
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void calculate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculate1ActionPerformed
        // TODO add your handling code here:
       DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
       model.addRow(new Object[]{book_name_jtext1.getText(), books_volume_jtext6.getText(), book_type_jtext2.getText(),books_price_jtext5.getText(),
       quantity_jtext6.getText(),vat_jtext8.getText(),price_jtext7.getText(),price_cal_jtext9.getText(),Withdrawal.getText()});
       
       
       SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
       String sele_day = sdf.format(date_sell.getDate());
       
       Connection conn = null;
        try {
            String base_URL = "jdbc:mysql://";
            String server = "localhost";
            String db = "sukuna_book_store";
            String u = "root";
            String p = "12345678";
            String con_string = base_URL + server + "/" + db;
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(con_string,u,p);
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        String sql = "INSERT INTO report values ( ?,?,?,?,?,?,?,?,?,?,?,?,?,?,? )"  ;

        try {
            PreparedStatement stmt = conn.prepareStatement(sql); //6
            
            stmt.setString(1, sele_day);
            stmt.setString(2, member_code_jtext.getText());
            stmt.setString(3, member_name_jtext1.getText());
            stmt.setString(4, member_Lastname_jtext2.getText());
            stmt.setString(5, member_phone_jtext3.getText());
            stmt.setString(6, member_gender_jtext4.getText());
            //book_name_jtext1
            stmt.setString(7, book_name_jtext1.getText());
            stmt.setString(8, books_volume_jtext6.getText());
            stmt.setString(9, book_type_jtext2.getText());
            stmt.setString(10, books_price_jtext5.getText());
            stmt.setString(11, quantity_jtext6.getText());
            stmt.setString(12, vat_jtext8.getText());
            stmt.setString(13, price_jtext7.getText());
            stmt.setString(14, price_cal_jtext9.getText());
            stmt.setString(15, Withdrawal.getText());
            
            
            stmt.executeUpdate();
            
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null,  e.getMessage());
        }
        
       
       
    }//GEN-LAST:event_calculate1ActionPerformed

    private void Back_To_MainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_To_MainActionPerformed
        // TODO add your handling code here:
        close();
        Main m = new Main();
        m.setVisible(true);
    }//GEN-LAST:event_Back_To_MainActionPerformed

    private void WithdrawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WithdrawalActionPerformed

    
    
    public void close()
    {
        WindowEvent closeWindows = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindows);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buy_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buy_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buy_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buy_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buy_book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_To_Main;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField Withdrawal;
    private javax.swing.JTextField book_name_jtext1;
    private javax.swing.JTextField book_type_jtext2;
    private javax.swing.JTextField books_price_jtext5;
    private javax.swing.JTextField books_volume_jtext6;
    private javax.swing.JButton calculate;
    private javax.swing.JButton calculate1;
    private javax.swing.JLabel call_number1;
    private javax.swing.JLabel call_number2;
    private com.toedter.calendar.JDateChooser date_sell;
    private javax.swing.JLabel gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel last_name;
    private javax.swing.JTextField member_Lastname_jtext2;
    private javax.swing.JTextField member_code_jtext;
    private javax.swing.JTextField member_gender_jtext4;
    private javax.swing.JTextField member_name_jtext1;
    private javax.swing.JTextField member_phone_jtext3;
    private javax.swing.JTextField price_cal_jtext9;
    private javax.swing.JTextField price_jtext7;
    private javax.swing.JTextField quantity_jtext6;
    private javax.swing.JTextField vat_jtext8;
    // End of variables declaration//GEN-END:variables
 
    private static class PrepareStatement {

      
    }
}
