/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import java.awt.event.WindowEvent;
import java.awt.Toolkit;
import javax.swing.JOptionPane;


/**
 *
 * @author Nonrapak
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Main() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Report = new javax.swing.JButton();
        Log_Out = new javax.swing.JButton();
        Return_Book = new javax.swing.JButton();
        Manage_Member_Ship = new javax.swing.JButton();
        Manage_Book = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(java.awt.Color.white);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pocket_monsters_2019_anime_logo_translation_by_sliter_ddomqsd-fullview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addContainerGap(830, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 50));

        Report.setFont(new java.awt.Font("Mali", 0, 24)); // NOI18N
        Report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excel (1).png"))); // NOI18N
        Report.setText("ออกรายงาน");
        Report.setBorder(null);
        Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportActionPerformed(evt);
            }
        });
        getContentPane().add(Report, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 250, 70));

        Log_Out.setFont(new java.awt.Font("Mali", 0, 24)); // NOI18N
        Log_Out.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout (1).png"))); // NOI18N
        Log_Out.setText("ออกจากระบบ");
        Log_Out.setBorder(null);
        Log_Out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_OutActionPerformed(evt);
            }
        });
        getContentPane().add(Log_Out, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, 250, 70));

        Return_Book.setFont(new java.awt.Font("Mali", 0, 24)); // NOI18N
        Return_Book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return-book-560235.png"))); // NOI18N
        Return_Book.setText("ซื้อหนังสือ");
        Return_Book.setBorder(null);
        Return_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return_BookActionPerformed(evt);
            }
        });
        getContentPane().add(Return_Book, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 210, 250, 70));

        Manage_Member_Ship.setFont(new java.awt.Font("Mali", 0, 24)); // NOI18N
        Manage_Member_Ship.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/member (1).png"))); // NOI18N
        Manage_Member_Ship.setText("จัดการสมาชิก");
        Manage_Member_Ship.setBorder(null);
        Manage_Member_Ship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manage_Member_ShipActionPerformed(evt);
            }
        });
        getContentPane().add(Manage_Member_Ship, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 250, 70));

        Manage_Book.setFont(new java.awt.Font("Mali", 0, 24)); // NOI18N
        Manage_Book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agenda (1).png"))); // NOI18N
        Manage_Book.setText("จัดการหนังสือ");
        Manage_Book.setBorder(null);
        Manage_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manage_BookActionPerformed(evt);
            }
        });
        getContentPane().add(Manage_Book, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 250, 70));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pikcachu1.gif"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 650, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG (3).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Manage_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_BookActionPerformed
        // TODO add your handling code here:
        close();
        ManageBooks mb = new ManageBooks();
        mb.setVisible(true);
    }//GEN-LAST:event_Manage_BookActionPerformed

    private void Manage_Member_ShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_Member_ShipActionPerformed
        // TODO add your handling code here:
        close();
        ManageMembership ms = new ManageMembership();
        ms.setVisible(true);
    }//GEN-LAST:event_Manage_Member_ShipActionPerformed

    private void Return_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return_BookActionPerformed
        // TODO add your handling code here:
        close();
        buy_book rs = new buy_book();
        rs.setVisible(true);
    }//GEN-LAST:event_Return_BookActionPerformed

    private void Log_OutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_OutActionPerformed
   // TODO add your handling code here:
        close();
        Login lg = new Login();
        lg.setVisible(true);
    }//GEN-LAST:event_Log_OutActionPerformed

    private void ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportActionPerformed
        // TODO add your handling code here:
        close();
        report rp = new report();
        rp.setVisible(true);
    }//GEN-LAST:event_ReportActionPerformed

    public void close()
    {
        WindowEvent closeWindows = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindows);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Log_Out;
    private javax.swing.JButton Manage_Book;
    private javax.swing.JButton Manage_Member_Ship;
    private javax.swing.JButton Report;
    private javax.swing.JButton Return_Book;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private static class PrepareStatement {

      
    }
}
