/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import java.awt.event.WindowEvent;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;


/**
 *
 * @author Nonrapak
 */
public class ManageMembership extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public ManageMembership() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SeachBar = new javax.swing.JTextField();
        SearchItem = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        EditMemberShip = new javax.swing.JButton();
        InsertMember = new javax.swing.JButton();
        DeleteMemberShip = new javax.swing.JButton();
        Excel = new javax.swing.JButton();
        Json = new javax.swing.JButton();
        Back_To_Main = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(java.awt.Color.white);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SeachBar.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(SeachBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 430, 30));

        SearchItem.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        SearchItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        SearchItem.setText("ค้นหา");
        SearchItem.setBorder(null);
        SearchItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchItemActionPerformed(evt);
            }
        });
        getContentPane().add(SearchItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 130, 30));

        jLabel4.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ค้นหาชื่อสมาชิก :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 150, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 820, 450));

        EditMemberShip.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        EditMemberShip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-account-member-user-profile-512.png"))); // NOI18N
        EditMemberShip.setText("เเก้ไขสมาชิก");
        EditMemberShip.setBorder(null);
        EditMemberShip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditMemberShipMouseClicked(evt);
            }
        });
        EditMemberShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditMemberShipActionPerformed(evt);
            }
        });
        getContentPane().add(EditMemberShip, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 250, 150, 60));

        InsertMember.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        InsertMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-2493635_960_720.png"))); // NOI18N
        InsertMember.setText("เพิ่มสมาชิก");
        InsertMember.setBorder(null);
        InsertMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InsertMemberMouseClicked(evt);
            }
        });
        InsertMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertMemberActionPerformed(evt);
            }
        });
        getContentPane().add(InsertMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, 150, 60));

        DeleteMemberShip.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        DeleteMemberShip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_remove_man_male_profile_account_person-512.png"))); // NOI18N
        DeleteMemberShip.setText("ลบสมาชิก");
        DeleteMemberShip.setBorder(null);
        DeleteMemberShip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMemberShipMouseClicked(evt);
            }
        });
        DeleteMemberShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteMemberShipActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteMemberShip, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 350, 150, 60));

        Excel.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        Excel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excel.png"))); // NOI18N
        Excel.setText("Export Excel");
        Excel.setBorder(null);
        Excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcelActionPerformed(evt);
            }
        });
        getContentPane().add(Excel, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 460, 150, 60));

        Json.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        Json.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/json.png"))); // NOI18N
        Json.setText("Export JSON");
        Json.setBorder(null);
        Json.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JsonActionPerformed(evt);
            }
        });
        getContentPane().add(Json, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 560, 150, 60));

        Back_To_Main.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        Back_To_Main.setText("Back To Main");
        Back_To_Main.setBorder(null);
        Back_To_Main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_To_MainActionPerformed(evt);
            }
        });
        getContentPane().add(Back_To_Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 660, 160, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pocket_monsters_2019_anime_logo_translation_by_sliter_ddomqsd-fullview.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bg2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    
    
    private void SearchItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchItemActionPerformed
        // TODO add your handling code here:
         String header[] = new String[]{"รหัสสมาชิก", "ชื่อสมาชิก","นามสกุลสมาชิก", "รหัสบัตรประชาชน", "วันเกิด", "เพศ", "ที่อยู่","เบอร์โทรศัพท์","วันที่สมัคสมาชิก"};
        DefaultTableModel dtm = new DefaultTableModel();
        jTable1.setModel(dtm);
        dtm.setColumnCount(7);
        dtm.setRowCount(1);
        dtm.setColumnIdentifiers(header);
        
        Connection conn = null;
        try {
            String base_URL = "jdbc:mysql://";
            String server = "localhost";
            String db = "sukuna_book_store";
            String u = "root";
            String p = "12345678";
            String con_string = base_URL + server + "/" + db;
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(con_string, u, p);
            
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        try {
            String sql = "SELECT * FROM managemember WHERE member_name = ? ORDER BY member_code ASC ";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, SeachBar.getText());
            ResultSet rs = stmt.executeQuery();// rs เก็บผลลัพธ์ของการค้นหาที่ return มาจาก MySQL
           
            
            int n = 0;
            while(rs.next()){
                					
                dtm.setValueAt( rs.getString("member_code"), n, 0);
                dtm.setValueAt( rs.getString("member_name"), n, 1);
                dtm.setValueAt( rs.getString("member_lastname"), n, 2);
                dtm.setValueAt( rs.getString("person_code"), n, 3);
                dtm.setValueAt( rs.getString("date"), n, 4);               
                dtm.setValueAt( rs.getString("gender"), n, 5);
                dtm.setValueAt( rs.getString("address"), n, 6); 
                dtm.setValueAt( rs.getString("call_number"), n, 7);
                dtm.setValueAt( rs.getString("member_register"), n, 8);
                  
                n++;//เพิ่มค่าตัวนับแถว
                dtm.setRowCount(n+1);//เพิ่มจำนวนแถวของ Jtable
            }
            
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
       
    }//GEN-LAST:event_SearchItemActionPerformed

    private void InsertMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertMemberMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertMemberMouseClicked

    private void InsertMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertMemberActionPerformed
        // TODO add your handling code here:
        close();
        AddMemberShip adm = new AddMemberShip();
        adm.setVisible(true);

    }//GEN-LAST:event_InsertMemberActionPerformed

    private void EditMemberShipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMemberShipMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EditMemberShipMouseClicked

    private void EditMemberShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditMemberShipActionPerformed
        // TODO add your handling code here:
        close();
       Update_Member Ub = new Update_Member();
       Ub.setVisible(true);
    }//GEN-LAST:event_EditMemberShipActionPerformed

    private void DeleteMemberShipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMemberShipMouseClicked
        // TODO add your handling code here:
        close();
        Delete_Member dm = new Delete_Member();
        dm.setVisible(true);
    }//GEN-LAST:event_DeleteMemberShipMouseClicked

    private void ExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcelActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();

        XSSFWorkbook workbook = new XSSFWorkbook();
        XSSFSheet sheet = workbook.createSheet("report");
        Row header = sheet.createRow(0);
        for (int j=0;j < dtm.getColumnCount(); j++) {
            Cell cell = header .createCell(j);
            String column_name = dtm.getColumnName(j);
            cell.setCellValue(column_name);
        }

        int rowNum = 1;

        for (int i=0;i < dtm.getRowCount(); i++) {
            Row row = sheet.createRow(rowNum++);
            int colNum = 0;
            for (int j=0;j < dtm.getColumnCount(); j++) {
                Cell cell = row.createCell(colNum++);
                String v = (String)dtm.getValueAt(i, j);
                cell.setCellValue(v);
            }
        }
        //แก้ที่นี่
        //String FILE_NAME = "C:\\Users\\IT\\Desktop\\text.xlsx";
        String FILE_NAME = "C:\\Users\\Nonrapak\\Desktop\\Databese_file.xlsx";
        try {
            FileOutputStream outputStream = new FileOutputStream(FILE_NAME);
            workbook.write(outputStream);
            workbook.close();
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        JOptionPane.showMessageDialog(null, "สร้างรายงานสำเร็จ");
    }//GEN-LAST:event_ExcelActionPerformed

    private void JsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JsonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
        String[] cols = new String[]{"รหัสสมาชิก", "ชื่อสมาชิก","นามสกุลสมาชิก", "รหัสบัตรประชาชน", "วันเกิด", "เพศ", "ที่อยู่","เบอร์โทรศัพท์","วันที่สมัคสมาชิก"};
        int rowNum = 1;
        String json = "[";
        for (int i=0;i < dtm.getRowCount()-1; i++) {
            int colNum = 0;
            String row = "{\n'" + cols[0] + "' : '" + dtm.getValueAt(i, 0) +"'";
            for (int j=1;j < dtm.getColumnCount(); j++) {
                String v = (String)dtm.getValueAt(i, j);
                row = row + ",\n'" + cols[j] + "' : '" + dtm.getValueAt(i, j) +"'";
            }
            row = row + "\n}";
            if(i==0)json = json + row;
            else json = json + "," +row;
        }
        json = json + "]";

        //แก้ตำแหน่งเขียนไฟล์ JSON
        String FILE_NAME = "C:\\Users\\Nonrapak\\Desktop\\Databese_file.json";
        try  {
            try (FileWriter file = new FileWriter(FILE_NAME)) {
                file.write(json);
            }
        } catch (IOException e) {
        }
        JOptionPane.showMessageDialog(null, "สร้าง JSON สำเร็จ");
    }//GEN-LAST:event_JsonActionPerformed

    private void DeleteMemberShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteMemberShipActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_DeleteMemberShipActionPerformed

    private void Back_To_MainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_To_MainActionPerformed
        // TODO add your handling code here:
        close();
        Main m = new Main();
        m.setVisible(true);
    }//GEN-LAST:event_Back_To_MainActionPerformed

    public void close()
    {
        WindowEvent closeWindows = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindows);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageMembership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageMembership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageMembership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageMembership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageMembership().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_To_Main;
    private javax.swing.JButton DeleteMemberShip;
    private javax.swing.JButton EditMemberShip;
    private javax.swing.JButton Excel;
    private javax.swing.JButton InsertMember;
    private javax.swing.JButton Json;
    private javax.swing.JTextField SeachBar;
    private javax.swing.JButton SearchItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private static class PrepareStatement {

      
    }
}
