/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import java.awt.event.WindowEvent;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.io.*;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;


/**
 *
 * @author Nonrapak
 */
public class ManageBooks extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public ManageBooks() {
        initComponents();
    }
   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        SeachBar = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        SearchItem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        InsertBook1 = new javax.swing.JButton();
        DeleteBook = new javax.swing.JButton();
        EditBook1 = new javax.swing.JButton();
        Excel = new javax.swing.JButton();
        Back_To_Main = new javax.swing.JButton();
        Json = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(java.awt.Color.white);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ค้นหาชื่อหนังสือ :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 80, 160, 30));

        SeachBar.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(SeachBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 430, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 670, -1, -1));

        SearchItem.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        SearchItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        SearchItem.setText("ค้นหา");
        SearchItem.setBorder(null);
        SearchItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchItemActionPerformed(evt);
            }
        });
        getContentPane().add(SearchItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 130, 30));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 850, 430));

        InsertBook1.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        InsertBook1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        InsertBook1.setText("เพิ่มหนังสือ");
        InsertBook1.setBorder(null);
        InsertBook1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InsertBook1MouseClicked(evt);
            }
        });
        InsertBook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertBook1ActionPerformed(evt);
            }
        });
        getContentPane().add(InsertBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 140, 150, 60));

        DeleteBook.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        DeleteBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book-with-cross-delete-symbol.png"))); // NOI18N
        DeleteBook.setText("ลบหนังสือ");
        DeleteBook.setBorder(null);
        DeleteBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteBookMouseClicked(evt);
            }
        });
        getContentPane().add(DeleteBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 350, 150, 60));

        EditBook1.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        EditBook1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        EditBook1.setText("เเก้ไขหนังสือ");
        EditBook1.setBorder(null);
        EditBook1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditBook1MouseClicked(evt);
            }
        });
        EditBook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBook1ActionPerformed(evt);
            }
        });
        getContentPane().add(EditBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 250, 150, 60));

        Excel.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        Excel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excel.png"))); // NOI18N
        Excel.setText("Export Excel");
        Excel.setBorder(null);
        Excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcelActionPerformed(evt);
            }
        });
        getContentPane().add(Excel, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 460, 150, 60));

        Back_To_Main.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        Back_To_Main.setText("Back To Main");
        Back_To_Main.setBorder(null);
        Back_To_Main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_To_MainActionPerformed(evt);
            }
        });
        getContentPane().add(Back_To_Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 660, 160, 60));

        Json.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        Json.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/json.png"))); // NOI18N
        Json.setText("Export JSON");
        Json.setBorder(null);
        Json.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JsonActionPerformed(evt);
            }
        });
        getContentPane().add(Json, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 560, 150, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pocket_monsters_2019_anime_logo_translation_by_sliter_ddomqsd-fullview.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, 50));

        jLabel3.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG (3).jpg"))); // NOI18N
        jLabel3.setText("jLabel1");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void SearchItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchItemActionPerformed
        // TODO add your handling code here:
         String header[] = new String[]{"ชื่อหนังสือ", "เล่มที่","ประเภทหนังสือ", "ชื่อผู้เขียน", "สำนักพิมพ์", "ราคา", "จำนวน"};
        DefaultTableModel dtm = new DefaultTableModel();
        jTable1.setModel(dtm);
        dtm.setColumnCount(7);
        dtm.setRowCount(1);
        dtm.setColumnIdentifiers(header);
        
        Connection conn = null;
        try {
            String base_URL = "jdbc:mysql://";
            String server = "localhost";
            String db = "sukuna_book_store";
            String u = "root";
            String p = "12345678";
            String con_string = base_URL + server + "/" + db;
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(con_string, u, p);
            
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        try {
            String sql = "SELECT * FROM managebooks WHERE book_name = ? ORDER BY book_volume ASC ";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, SeachBar.getText());
            ResultSet rs = stmt.executeQuery();// rs เก็บผลลัพธ์ของการค้นหาที่ return มาจาก MySQL
           
            
            int n = 0;
            while(rs.next()){
                					
                dtm.setValueAt( rs.getString("book_name"), n, 0);
                dtm.setValueAt( rs.getString("book_volume"), n, 1);
                dtm.setValueAt( rs.getString("book_type"), n, 2);
                dtm.setValueAt( rs.getString("publisher"), n, 3);
                dtm.setValueAt( rs.getString("author_name"), n, 4);               
                dtm.setValueAt( rs.getString("price"), n, 5);
                dtm.setValueAt( rs.getString("quantity"), n, 6); // แสดงผล Country แถวที่ n และ คอลัมที่ 4
                n++;//เพิ่มค่าตัวนับแถว
                dtm.setRowCount(n+1);//เพิ่มจำนวนแถวของ Jtable
            }
            
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
       
    }//GEN-LAST:event_SearchItemActionPerformed

    private void InsertBook1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertBook1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertBook1MouseClicked

    private void InsertBook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertBook1ActionPerformed
        // TODO add your handling code here:
        close();
        AddBook ad = new AddBook();
        ad.setVisible(true);
       
    }//GEN-LAST:event_InsertBook1ActionPerformed

    private void DeleteBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteBookMouseClicked
        // TODO add your handling code here:
        close();
        Delete_Book ub = new Delete_Book();
        ub.setVisible(true);
    }//GEN-LAST:event_DeleteBookMouseClicked

    private void EditBook1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBook1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EditBook1MouseClicked

    private void EditBook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBook1ActionPerformed
        // TODO add your handling code here:
        close();
        Update_Book ed = new Update_Book();
        ed.setVisible(true);
    }//GEN-LAST:event_EditBook1ActionPerformed

    private void ExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcelActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
        
        XSSFWorkbook workbook = new XSSFWorkbook();
        XSSFSheet sheet = workbook.createSheet("report");
        Row header = sheet.createRow(0);
        for (int j=0;j < dtm.getColumnCount(); j++) {
          Cell cell = header .createCell(j);
          String column_name = dtm.getColumnName(j);
          cell.setCellValue(column_name);
        }
        
        int rowNum = 1;
  
        for (int i=0;i < dtm.getRowCount(); i++) {
            Row row = sheet.createRow(rowNum++);
            int colNum = 0;
            for (int j=0;j < dtm.getColumnCount(); j++) {
                Cell cell = row.createCell(colNum++);
                String v = (String)dtm.getValueAt(i, j);
                cell.setCellValue(v);
            }
        }
        //แก้ที่นี่
       //String FILE_NAME = "C:\\Users\\IT\\Desktop\\text.xlsx";
       String FILE_NAME = "C:\\Users\\Nonrapak\\Desktop\\Databese_file.xlsx";
        try {
            FileOutputStream outputStream = new FileOutputStream(FILE_NAME);
            workbook.write(outputStream);
            workbook.close();
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch (IOException e) {
           JOptionPane.showMessageDialog(null, e.getMessage());
        }
        JOptionPane.showMessageDialog(null, "สร้างรายงานสำเร็จ");
    }//GEN-LAST:event_ExcelActionPerformed

    private void JsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JsonActionPerformed
        // TODO add your handling code here:
       DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
       String[] cols = new String[]{"ชื่อหนังสือ", "เล่มที่","ประเภทหนังสือ", "ชื่อผู้เขียน", "สำนักพิมพ์", "ราคา", "จำนวน"};
         int rowNum = 1;
        String json = "[";
        for (int i=0;i < dtm.getRowCount()-1; i++) {
            int colNum = 0;
            String row = "{\n'" + cols[0] + "' : '" + dtm.getValueAt(i, 0) +"'";
            for (int j=1;j < dtm.getColumnCount(); j++) {
                String v = (String)dtm.getValueAt(i, j);
                row = row + ",\n'" + cols[j] + "' : '" + dtm.getValueAt(i, j) +"'"; 
            }
            row = row + "\n}";
            if(i==0)json = json + row;
            else json = json + "," +row;
        }
        json = json + "]";
        
       //แก้ตำแหน่งเขียนไฟล์ JSON       
       String FILE_NAME = "C:\\Users\\Nonrapak\\Desktop\\Databese_file.json";
        try  {
           try (FileWriter file = new FileWriter(FILE_NAME)) {
               file.write(json);
           }
        } catch (IOException e) {
        }
        JOptionPane.showMessageDialog(null, "สร้าง JSON สำเร็จ");
    }//GEN-LAST:event_JsonActionPerformed

    private void Back_To_MainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_To_MainActionPerformed
        // TODO add your handling code here:
        close();
        Main m = new Main();
        m.setVisible(true);
    }//GEN-LAST:event_Back_To_MainActionPerformed

    public void close()
    {
        WindowEvent closeWindows = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindows);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
       



        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_To_Main;
    private javax.swing.JButton DeleteBook;
    private javax.swing.JButton EditBook1;
    private javax.swing.JButton Excel;
    private javax.swing.JButton InsertBook1;
    private javax.swing.JButton Json;
    private javax.swing.JTextField SeachBar;
    private javax.swing.JButton SearchItem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private static class PrepareStatement {

      
    }
}
