/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import java.awt.HeadlessException;
import java.awt.event.WindowEvent;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Nonrapak
 */
public class Update_Book extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Update_Book() {
        initComponents();
        showTableData();
    }

    
    
    public void showTableData()
    {
        String header[] = new String[]{"ชื่อหนังสือ", "เล่มที่","ประเภทหนังสือ", "ชื่อผู้เขียน", "สำนักพิมพ์", "ราคา", "จำนวน"};
        DefaultTableModel dtm = new DefaultTableModel();
        jTable1.setModel(dtm);
        dtm.setColumnCount(7);
        dtm.setRowCount(1);
        dtm.setColumnIdentifiers(header);
        
        Connection conn = null;
        try {
            String base_URL = "jdbc:mysql://";
            String server = "localhost";
            String db = "sukuna_book_store";
            String u = "root";
            String p = "12345678";
            String con_string = base_URL + server + "/" + db;
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(con_string, u, p);
            
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        try {
            String sql = "SELECT * FROM managebooks ORDER BY book_volume";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();// rs เก็บผลลัพธ์ของการค้นหาที่ return มาจาก MySQL
           
            
            int n = 0;
            while(rs.next()){
                					
                dtm.setValueAt( rs.getString("book_name"), n, 0);
                dtm.setValueAt( rs.getString("book_volume"), n, 1);
                dtm.setValueAt( rs.getString("book_type"), n, 2);
                dtm.setValueAt( rs.getString("publisher"), n, 3);
                dtm.setValueAt( rs.getString("author_name"), n, 4);               
                dtm.setValueAt( rs.getString("price"), n, 5);
                dtm.setValueAt( rs.getString("quantity"), n, 6); // แสดงผล Country แถวที่ n และ คอลัมที่ 4
                n++;//เพิ่มค่าตัวนับแถว
                dtm.setRowCount(n+1);//เพิ่มจำนวนแถวของ Jtable
            }
            
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Book_quantity_jtext5 = new javax.swing.JTextField();
        Book_price_jtext4 = new javax.swing.JTextField();
        publisher_jtext3 = new javax.swing.JTextField();
        author_name = new javax.swing.JTextField();
        Book_type_jtext1 = new javax.swing.JTextField();
        Book_value_jtext1 = new javax.swing.JTextField();
        Book_name_jtext = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        update_book = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Back = new javax.swing.JButton();
        SeachBar = new javax.swing.JTextField();
        SearchItem = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(java.awt.Color.white);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Book_quantity_jtext5.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(Book_quantity_jtext5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 510, 260, 30));

        Book_price_jtext4.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(Book_price_jtext4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 450, 260, 30));

        publisher_jtext3.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(publisher_jtext3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 380, 260, 30));

        author_name.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(author_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 310, 260, 30));

        Book_type_jtext1.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(Book_type_jtext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 240, 260, 30));

        Book_value_jtext1.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(Book_value_jtext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 170, 260, 30));

        Book_name_jtext.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(Book_name_jtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 90, 260, 30));

        jLabel16.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("จำนวน :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 450, 80, 30));

        jLabel15.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("เล่มที่ :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 170, 60, 30));

        jLabel14.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ราคา :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 510, 60, 30));

        jLabel13.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("สำนักพิพม์ :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 380, 100, 30));

        jLabel12.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ผู้เขียน :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 310, 70, 30));

        jLabel10.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ประเภทหนังสือ :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, 150, 30));

        jLabel9.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ชื่อหนังสือ :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 90, 100, 30));

        update_book.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        update_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        update_book.setText("เเก้ไขหนังสือ");
        update_book.setBorder(null);
        update_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_bookActionPerformed(evt);
            }
        });
        getContentPane().add(update_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, 150, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 730, 500));

        Back.setFont(new java.awt.Font("Mali", 0, 20)); // NOI18N
        Back.setText("Back");
        Back.setBorder(null);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 660, 130, 60));

        SeachBar.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        getContentPane().add(SeachBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 430, 30));

        SearchItem.setFont(new java.awt.Font("Mali", 0, 16)); // NOI18N
        SearchItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        SearchItem.setText("ค้นหา");
        SearchItem.setBorder(null);
        SearchItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchItemActionPerformed(evt);
            }
        });
        getContentPane().add(SearchItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 130, 30));

        jLabel4.setFont(new java.awt.Font("Mali", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ค้นหาชื่อหนังสือ :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pocket_monsters_2019_anime_logo_translation_by_sliter_ddomqsd-fullview.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void update_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_bookActionPerformed
       Connection conn = null;
         try {  
            String base_URL = "jdbc:mysql://";
            String server = "localhost";
            String db = "sukuna_book_store";
            String u = "root";
            String p = "12345678";
            String con_string = base_URL + server + "/" + db;
            Class.forName("com.mysql.jdbc.Driver");
        conn = DriverManager.getConnection(con_string,u,p);
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
         
         String sql = "UPDATE managebooks set   book_type = ?, publisher = ?, author_name = ?, quantity = ?, price = ? WHERE book_name = ? "  ;
         
           try {
            PreparedStatement stmt = conn.prepareStatement(sql); //6
            stmt.setString(6, Book_name_jtext.getText());
            stmt.setString(1, Book_type_jtext1.getText());
            stmt.setString(2, author_name.getText());
            stmt.setString(3, publisher_jtext3.getText());
            stmt.setString(4, Book_price_jtext4.getText());
            stmt.setString(5, Book_quantity_jtext5.getText());
             stmt.executeUpdate(); 
             JOptionPane.showMessageDialog(null, "เพิ่มข้อมูลสำเร็จ");
             }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null,  e.getMessage());
        }        // TODO add your handling code here:
        showTableData();
     
    }//GEN-LAST:event_update_bookActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        close();
        this.toBack();
        ManageBooks mb = new ManageBooks();
        mb.setVisible(true);
        mb.toFront();
    }//GEN-LAST:event_BackActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selectedRowIndex = jTable1.getSelectedRow();
        
        Book_name_jtext.setText(model.getValueAt(selectedRowIndex, 0).toString());
        Book_value_jtext1.setText(model.getValueAt(selectedRowIndex, 1).toString());
        Book_type_jtext1.setText(model.getValueAt(selectedRowIndex, 2).toString());
        author_name.setText(model.getValueAt(selectedRowIndex, 3).toString());
        publisher_jtext3.setText(model.getValueAt(selectedRowIndex, 4).toString());
        Book_price_jtext4.setText(model.getValueAt(selectedRowIndex, 5).toString());
        Book_quantity_jtext5.setText(model.getValueAt(selectedRowIndex, 6).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void SearchItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchItemActionPerformed
        // TODO add your handling code here:
        String header[] = new String[]{"ชื่อหนังสือ", "เล่มที่","ประเภทหนังสือ", "ชื่อผู้เขียน", "สำนักพิมพ์", "ราคา", "จำนวน"};
        DefaultTableModel dtm = new DefaultTableModel();
        jTable1.setModel(dtm);
        dtm.setColumnCount(7);
        dtm.setRowCount(1);
        dtm.setColumnIdentifiers(header);

        Connection conn = null;
        try {
            String base_URL = "jdbc:mysql://";
            String server = "localhost";
            String db = "sukuna_book_store";
            String u = "root";
            String p = "12345678";
            String con_string = base_URL + server + "/" + db;
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(con_string, u, p);

        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        try {
            String sql = "SELECT * FROM managebooks WHERE book_name = ? ORDER BY book_volume ";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, SeachBar.getText());
            ResultSet rs = stmt.executeQuery();// rs เก็บผลลัพธ์ของการค้นหาที่ return มาจาก MySQL

            int n = 0;
            while(rs.next()){

                dtm.setValueAt( rs.getString("book_name"), n, 0);
                dtm.setValueAt( rs.getString("book_volume"), n, 1);
                dtm.setValueAt( rs.getString("book_type"), n, 2);
                dtm.setValueAt( rs.getString("publisher"), n, 3);
                dtm.setValueAt( rs.getString("author_name"), n, 4);
                dtm.setValueAt( rs.getString("price"), n, 5);
                dtm.setValueAt( rs.getString("quantity"), n, 6); // แสดงผล Country แถวที่ n และ คอลัมที่ 4
                n++;//เพิ่มค่าตัวนับแถว
                dtm.setRowCount(n+1);//เพิ่มจำนวนแถวของ Jtable
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_SearchItemActionPerformed

    public void close()
    {
        WindowEvent closeWindows = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindows);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField Book_name_jtext;
    private javax.swing.JTextField Book_price_jtext4;
    private javax.swing.JTextField Book_quantity_jtext5;
    private javax.swing.JTextField Book_type_jtext1;
    private javax.swing.JTextField Book_value_jtext1;
    private javax.swing.JTextField SeachBar;
    private javax.swing.JButton SearchItem;
    private javax.swing.JTextField author_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField publisher_jtext3;
    private javax.swing.JButton update_book;
    // End of variables declaration//GEN-END:variables

    private static class PrepareStatement {

      
    }
}
